trigger:
  branches:
    include:
      - master  
pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.302' 

  - task: MSBuild@1
    inputs:
      solution: '**/testdb/testdb.sqlproj'
      msbuildArchitecture: 'x64'
      msbuildArguments: '/p:NetCoreBuild=true'


  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
