trigger:
  branches:
    include:
      - master  
pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.302' 

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sqlproj'  

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
