# build-pipeline.yml
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: Build
        displayName: "Build Job"
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.0.302'  

          - task: VSBuild@1
            displayName: "Build Solution"
            inputs:
              solution: '**/*.sln'  
              msbuildArgs: '/p:Configuration=Release'  
              platform: 'Any CPU'
              configuration: 'Release'
          
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifacts"
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/testdb/bin/Release'  
              ArtifactName: 'drop'
